### ISSUE TITLE
Tidy up fallout of #313/#311

### ISSUE THREAD

**Issue by chrisprice** [ScottLogic/d3-financial-components#315]
* [x] #311 introduced a new chart layout which is appropriate for replacing the chart builder in #313.
* [x] #313 introduced the concept of simplified visual tests, #311 added a complex multi visual test which should be simplified.
* [x] #313 set an [explicit width on the iframe](https://github.com/ScottLogic/d3-financial-components/pull/313/files#diff-d03ea6571b32bddbca4b7f3afede1b2cL23), this should be removed if possible.
